version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-node1
    restart: always
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native client
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - ./data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: test_db
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin123
    ulimits:
      nofile:
        soft: 262144
        hard: 262144